version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - CMD_BUILD_DIR=queue-mgr-rest

    ports:
      - 8001:8001

    environment:

      # service
      QUEUE_MGR_TIME_BTW_JOB_PROCESSES: "10s"

      # httpserver
      HTTPSERVER_HOSTNAME: "0.0.0.0"
      HTTPSERVER_HOST_PORT: 8001
      HTTPSERVER_READ_HEADER_TIMEOUT_DURATION: "5s"
      HTTPSERVER_WRITE_TIMEOUT_DURATION: "5s"

      # Duration Strings (see timeouts).
      # A duration string is a possibly signed sequence of decimal numbers,
      # each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m".
      # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".